---
- name: Understanding Variables
  hosts: all
  become: yes
    #vars:
    # USRNM: playbook
    # COMM: Straight oughta Playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: msg

    - debug:
        var: msg.name
    - debug:
        var: msg.comment
