---
- name: DBserver Setup
  hosts: dbservers
  become: yes
    # vars:
    #dbname: electric
    #dbuser: current
    #dbpass: tesla
  tasks:
    - name: Installing mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Installing PyMySQL
      ansible.builtin.yum:
        name: python3-PyMySQL 
        state: present

    - name: Starting Service and Enabaling
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Creating Databases
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database user
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
