---
- name: Provisioning Servers
  hosts: all
  become: yes
  tasks:
    - name: Installing NTP Agent in CentOS
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS"

    - name: Installing NTP Agent in Ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Starting NTP Agent in CentOS
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Starting NTP Agent in Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
